### PR TITLE
fix: SendRequest action mapper

### LINKED ISSUE #894: SendRequest crash app when return is not a Int or Object
## Description
When receiving a value diferent of Int or Object through SendRequest, the application fails.. 

## Steps To Reproduce

1. Run Onboard BFF
2. Run MFI Android App
3. In login screen click in "acessar com outra conta"
4. Click in continue button

## Expected Results
Hope the app not crash

## Code example, screenshot, or link to a repository:

BFF, branch **feature/empty_response_test**
https://github.com/ZupIT/mfi-onboarding-bff

Android, branch **master**
https://github.com/ZupIT/mfi-app-mobile

### PR DESCRIPTION
**Pull request by paulomeurerzup**
### Related Issues

Closes #894 

### Checklist

Please, check if these important points are met using `[x]`:

- [X] I read the [PR Guide] and followed the process outlined there for submitting this PR.
- [X] I avoided _breaking changes_ by not changing public APIs that people rely on. 
- [X] I am willing to follow-up on review comments in a timely manner.

[PR Guide]: https://github.com/ZupIT/beagle/blob/master/doc/contributing/pull_requests.md

### CODE REVIEW

**Review by matheusribeirozup — APPROVED** [review]

File: android/beagle/src/main/java/br/com/zup/beagle/android/view/mapper/SendRequestActionMapper.kt [hunk 1]
```diff
@@ -67,6 +67,14 @@ internal object SendRequestActionMapper {
...
         } catch (e: NumberFormatException) {
+            deserializeObjectOrGetRawString(data)
+        } catch (e: Exception) {
+            data
+        }
+    }
+
+    private fun deserializeObjectOrGetRawString(data: String): Any? {
+        return try {
             BeagleMoshi.moshi.adapter(Any::class.java).fromJson(data)
```
Comment (tuliopereirazup) [inline android/beagle/src/main/java/br/com/zup/beagle/android/view/mapper/SendRequestActionMapper.kt:78]: Here you can use change to:
```suggestion
            BeagleMoshi.moshi.adapter(Any::class.java, ContextDataValue::class.java).fromJson(data)
```

To make sure this Any will be deserialised correctly using the `ContextDataAdapterFactory`.

File: android/beagle/src/test/java/br/com/zup/beagle/android/view/mapper/SendRequestActionMapperTest.kt [hunk 2]
```diff
@@ -0,0 +1,87 @@
...
+        val responseData = ResponseData(
+            statusCode = 200,
+            data = "{\"result\":\"test\"}".toByteArray()
+        )
+
+        //When
+        val response = SendRequestActionMapper.toResponse(responseData)
+
+        //Then
+        assert(response.data is Any)
```
Comment (tuliopereirazup) [inline android/beagle/src/test/java/br/com/zup/beagle/android/view/mapper/SendRequestActionMapperTest.kt:53]: Maybe you could change this assert to:
```suggestion
       val jsonObject = response.data is JSONObject
        assertEquals("test", jsonObject.getString("result"))
```

Because the expected is to convert a JSON String to a valid context data value.
Maybe you should create another cases, like JSONArray, double, int, boolean.

Comment (gabrielleonardozup) [reply android/beagle/src/test/java/br/com/zup/beagle/android/view/mapper/SendRequestActionMapperTest.kt:53]: Or even create other test case for this suggested assertion, because the actual assertion make sense with THEN clause in test case.

File: android/beagle/src/main/java/br/com/zup/beagle/android/view/mapper/SendRequestActionMapper.kt (hunk 1 above)
Comment (paulomeurerzup) [reply android/beagle/src/main/java/br/com/zup/beagle/android/view/mapper/SendRequestActionMapper.kt]: done

File: android/beagle/src/test/java/br/com/zup/beagle/android/view/mapper/SendRequestActionMapperTest.kt (hunk 2 above)
Comment (paulomeurerzup) [reply android/beagle/src/test/java/br/com/zup/beagle/android/view/mapper/SendRequestActionMapperTest.kt]: added new test cases

**Review by jefersonlopeszup — APPROVED** [review]

File: android/beagle/src/test/java/br/com/zup/beagle/android/view/mapper/SendRequestActionMapperTest.kt (hunk 2 above)
Comment (tuliopereirazup) [reply android/beagle/src/test/java/br/com/zup/beagle/android/view/mapper/SendRequestActionMapperTest.kt]: It's missing only the JSONArray test and we can go.

Comment (paulomeurerzup) [reply android/beagle/src/test/java/br/com/zup/beagle/android/view/mapper/SendRequestActionMapperTest.kt]: added

**Review by matheusribeirozup — APPROVED** [review]

**Review by tuliopereirazup — APPROVED** [review]
