### PR TITLE
fix: show place holder and error when loading and the request url error

### LINKED ISSUE #783: Context error: jsonDataException when use declarative on Android
### Description

Using the same declarative code as BFF on the front, ImagePath returns an error when used with context.

```
  Screen(
      child = Container(
                context = ContextData(
                    id = "teste",
                    value = Teste(
                        image = ImagePath.Remote("https://cdn-images-1.medium.com/max/1200/1*kjiNJPB3Y-ZVmjxco_bORA.png"),
                        description = "Imagem de teste"
                    )
                ),
                children = listOf(
                    Image(
                        path = expressionOf("@{teste.image}")
                    ),
                    Text(text = "Opa!!!")
                )
            )
        )
```

### PR DESCRIPTION
**Pull request by uziasferreirazup**
### Related Issues

Closes #783

### Description and Example

Fix image load in declarative android with place holder and error.

### Checklist

Please, check if these important points are met using `[x]`:

- [X] I read the [PR Guide] and followed the process outlined there for submitting this PR.
- [X] I avoided _breaking changes_ by not changing public APIs that people rely on. 
- [X] I am willing to follow-up on review comments in a timely manner.

[PR Guide]: https://github.com/ZupIT/beagle/blob/master/doc/contributing/pull_requests.md

### CODE REVIEW

File: android/beagle/src/main/java/br/com/zup/beagle/android/components/Image.kt [hunk 1]
```diff
@@ -88,27 +90,29 @@ data class Image(
...
+        imageView.loadImage(pathType)
     }
 
-    @SuppressLint("CheckResult")
-    private fun getGlideRequestOptions(placeholder: String?): RequestOptions {
-        val requestOptions = RequestOptions()
+    private fun setPlaceHolder(placeholder: String?, imageView: ImageView) {
         getImage(placeholder)?.let {
-            requestOptions.placeholder(it)
+            imageView.setImageDrawable(ContextCompat.getDrawable(imageView.context, it))
```
Comment (matheusribeirozup) [inline android/beagle/src/main/java/br/com/zup/beagle/android/components/Image.kt:99]: What do you think of using another method so you don't need to do this type conversion?
```suggestion
            imageView.setImageResource(it)
```
