### PR TITLE
fix: coexisting cache filters with CORS

### LINKED ISSUE #482: Cache mechanism doesn't work with CORS
## Description
Please provide a clear and concise description of what the bug is. Include screenshots if needed.
Please test using the latest Beagle release to make sure your issue has not already been fixed: https://github.com/ZupIT/beagle/releases

When sending a request with a valid beagle-hash from the Web (considering the existence of CORS) the request is not processed due to CORS problems with the response headers when a 304 is the response status.
The resulted error:

```
Access to fetch at 'http://localhost:8080/components' from origin 'http://localhost:4200' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
GET http://localhost:8080/components net::ERR_FAILED
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Send a request from the web with a valid beagle-hash which should trigger the cache mechanism return 304

## Expected Results
Describe what you expected to happen.
The request which results in a 304 should be correctly returned so that the web can handle it

## Code example, screenshot, or link to a repository:
Please provide a link to a repository on GitHub, or provide a minimal code example that reproduces the problem.
You may provide a screenshot of the application if you think it is relevant to your bug report.
Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

### PR DESCRIPTION
**Pull request by LG95**
## Description

Exposed our custom headers in Spring sample BFF's CORS configuration. 
Only caching the HTTP `GET` method, since the mechanism is not suited for others.
Configured CORS in Micronaut sample BFF.

## Related Issues

Fixes #482.

## Tests

I updated Spring starter's `BeagleCacheFilterTest` with scenarios for the HTTP methods `GET` and non-`GET`.

## Checklist

Before you create this PR, confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I signed the [DCO].
- [X] All existing and new tests are passing.
- [X] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [X] No, no existing tests failed, so this is *not* a breaking change.

[issue database]: https://github.com/ZupIT/beagle/issues
[DCO]: https://developercertificate.org/

### CODE REVIEW

File: backend/sample/spring/src/main/kotlin/br/com/zup/beagle/sample/spring/config/CorsConfig.kt [hunk 1]
```diff
@@ -33,6 +35,7 @@ open class CorsConfig {
                     .allowedOrigins("*")
                     .allowedMethods("*")
                     .allowedHeaders("*")
+                    .exposedHeaders(BeagleCacheHandler.CACHE_HEADER, BeaglePlatformUtil.BEAGLE_PLATFORM_HEADER)
```
Comment (ze12augusto) [inline backend/sample/spring/src/main/kotlin/br/com/zup/beagle/sample/spring/config/CorsConfig.kt:38]: We could have some way of informing the custom beagle headers

File: backend/starters/beagle-spring-starter/src/main/kotlin/br/com/zup/beagle/spring/filter/BeagleCacheFilter.kt [hunk 2]
```diff
@@ -30,7 +32,8 @@ import javax.servlet.http.HttpServletResponse
 class BeagleCacheFilter(private val cacheHandler: BeagleCacheHandler) : Filter {
     override fun doFilter(request: ServletRequest?, response: ServletResponse?, chain: FilterChain?) {
         if (chain != null && request is HttpServletRequest && response is HttpServletResponse) {
-            this.cacheHandler.handleCache(
+            if (request.method.toUpperCase(Locale.ROOT) == HttpMethod.OPTIONS.name) chain.doFilter(request, response)
```
Comment (ze12augusto) [inline backend/starters/beagle-spring-starter/src/main/kotlin/br/com/zup/beagle/spring/filter/BeagleCacheFilter.kt:35]: Change cache logic, to cache only in GET methods

File: backend/framework/src/main/kotlin/br/com/zup/beagle/constants/CorsConstants.kt [hunk 3]
```diff
@@ -0,0 +1,22 @@
...
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+
+package br.com.zup.beagle.constants
+
+import br.com.zup.beagle.cache.BeagleCacheHandler
+import br.com.zup.beagle.platform.BeaglePlatformUtil
+
+val BEAGLE_EXPOSED_HEADERS = arrayOf(BeagleCacheHandler.CACHE_HEADER)
```
Comment (ze12augusto) [inline backend/framework/src/main/kotlin/br/com/zup/beagle/constants/CorsConstants.kt:22]: Add Beagle Platform header

Comment (LG95) [reply backend/framework/src/main/kotlin/br/com/zup/beagle/constants/CorsConstants.kt:22]: It doesn't need to be exposed since it isn't returned, just received.

**Comment by LG95** [comment]
> The layout of the exposed headers was pretty cool, just missing a micronaut implementation now

Given Micronaut's property-based configuration, using the constant from `framework` is a complex problem. This problem is strays from the purpose of this fix which is to resolve issues between our starter's caching filters and CORS configuration. I believe it is best tackled in a separate issue and pull request.
