### PR TITLE
fix: page view crash with empty array of pages and breaking constraints

### LINKED ISSUE #420: Crash at PageViewUIComponent
**Describe the problem**
When creating a PageView component and put an empty array of children the app crashes.

**Expected behavior**
The app should show an empty screen.

Source of the error:
PageViewUIComponent.swift
```
private(set) lazy var pageViewController: UIPageViewController = {
    let pager = UIPageViewController(transitionStyle: .scroll, navigationOrientation: .horizontal, options: nil)
    pager.setViewControllers(
        [**model.pages[0]**], direction: .forward, animated: true, completion: nil
    )
    pager.dataSource = self
    pager.delegate = self
    return pager
}()
```

Exemple:

```
let screen = Screen(
    child: PageView(children: [], pageIndicator: PageIndicator(selectedColor: "d1d1d1", unselectedColor: "000000"))
)
```

### LINKED ISSUE #421: PageViewUIComponent's broken constraints
**Describe the problem**
When using a PageView Component the constraints are getting broken and showing in the debug log.

**Expected behavior**
The constraints should not break.

Exemples:

```
let screen = Screen(
    child: PageView(children: [Text("")], pageIndicator: PageIndicator(selectedColor: "d1d1d1", unselectedColor: "000000"))
)
```

```
(
    "<NSAutoresizingMaskLayoutConstraint:0x600003498690 h=--& v=--& Beagle.PageViewUIComponent:0x7fefe840a4f0.height == 0   (active)>",
    "<NSLayoutConstraint:0x600003490d20 V:|-(0)-[UIStackView:0x7fefe8705130]   (active, names: '|':Beagle.PageViewUIComponent:0x7fefe840a4f0 )>",
    "<NSLayoutConstraint:0x600003490dc0 UIStackView:0x7fefe8705130.bottom == Beagle.PageViewUIComponent:0x7fefe840a4f0.bottom   (active)>",
    "<NSLayoutConstraint:0x6000034b3160 'UISV-canvas-connection' UIStackView:0x7fefe8705130.top == _UIPageViewControllerContentView:0x7fefe8704770.top   (active)>",
    "<NSLayoutConstraint:0x6000034b31b0 'UISV-canvas-connection' V:[Beagle.PageIndicatorUIComponent:0x7fefe87071e0]-(0)-|   (active, names: '|':UIStackView:0x7fefe8705130 )>",
    "<NSLayoutConstraint:0x600003495c70 'UISV-spacing' V:[_UIPageViewControllerContentView:0x7fefe8704770]-(10)-[Beagle.PageIndicatorUIComponent:0x7fefe87071e0]   (active)>"
)
```

### PR DESCRIPTION
**Pull request by yandiaszup**
## Description

*Fix PageView crash when the list of pages is empty
 Fix PageView breaking constraints warnings*

## Related Issues

Fix #420
Fix #421

## Tests

I added the following tests:

`test_viewWithNoPages` at PageViewTests

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [DCO].
- [x] All existing and new tests are passing.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*

### CODE REVIEW

File: iOS/Sources/Beagle/Sources/Components/Page+Renderable/PageViewUIComponent.swift [hunk 1]
```diff
@@ -87,6 +87,11 @@ class PageViewUIComponent: UIView {
         stack.spacing = 10
         return stack
     }()
+    
+    override func layoutSubviews() {
```
Comment (theffc) [inline iOS/Sources/Beagle/Sources/Components/Page+Renderable/PageViewUIComponent.swift:91]: `layoutSubviews` can be called many times in a view lifecycle due to some change of positioning, and so, it should not trigger addition of subviews (unless properly handled) like it happens when calling `setupLayout`

File: iOS/Sources/Beagle/Sources/Components/Page+Renderable/PageViewUIComponent.swift [hunk 2]
```diff
@@ -71,36 +71,30 @@ class PageViewUIComponent: UIView {
...
-
-        addSubview(stackView)
-        stackView.translatesAutoresizingMaskIntoConstraints = false
-        stackView.anchor(top: topAnchor, left: leftAnchor, bottom: bottomAnchor, right: rightAnchor)
-
-        stackView.addArrangedSubview(view)
-
+        let pager: UIView = pageViewController.view
+        pager.yoga.flexGrow = 1
+        pager.yoga.isEnabled = true
```
Comment (lucasaraujo) [inline iOS/Sources/Beagle/Sources/Components/Page+Renderable/PageViewUIComponent.swift:86]: `pager.style.setup(...)` or `pager.beagle.setup(style: ...)` should be preferred to ensure the use of the  beagle default values when not specified.
