### PR TITLE
fix: android webview without defined size

### LINKED ISSUE #645: Android WebView it's not working properly
## Description
WebView it's not loading its content.

## Steps To Reproduce
See the code below.

## Expected Results
Independently of the scenario webview should render its content.

## Code example, screenshot, or link to a repository:
```kotlin
private fun actors() = ListView(
        direction = ListDirection.VERTICAL,
        children = listOf(
            Touchable(
                child = containerActors(
                    "https://m.media-amazon.com/images/M/MV5BZjM2NWVhNDItZjBmZS00YzYzLTk4NGUtYzE5YzI4NmZhOTE1XkEyXkFqcGdeQXVyNjA5ODQwNTA@._V1_UX32_CR0,0,32,44_AL_.jpg",
                    "Louis Hofmann"
                ), onPress = listOf(
                Navigate.PushView(
                    Route.Local(
                        Screen(
                            navigationBar = NavigationBar(
                                title = "Louis Hofmann - WebView",
                                showBackButton = true
                            ),
                            child = Container(
                                children = listOf(
                                    WebView("https://docs.usebeagle.io/")
                                )
                            ).applyStyle(
                                Style(
                                    flex = Flex(
                                        grow = 1.0,
                                        flexDirection = FlexDirection.COLUMN,
                                        justifyContent = JustifyContent.FLEX_START
                                    ),
                                    backgroundColor = "#6C6C6C"
                                )
                            )
                        )
                    )
                )
            )
            ),
            containerActors(
                "https://m.media-amazon.com/images/M/MV5BMjQ1MTE2ODc4N15BMl5BanBnXkFtZTgwNjAyNDkyNDM@._V1_UX32_CR0,0,32,44_AL_.jpg",
                "Karoline Eichhorn"
            ),
            containerActors(
                "https://m.media-amazon.com/images/M/MV5BMTU5NjI4MzI4MV5BMl5BanBnXkFtZTgwNDI5MjIzNDM@._V1_UX32_CR0,0,32,44_AL_.jpg",
                "Lisa Vicari"
            ),
            containerActors(
                "https://m.media-amazon.com/images/M/MV5BMjMzNjUxMDk0MF5BMl5BanBnXkFtZTgwMjY1OTgyNDM@._V1_UY44_CR17,0,32,44_AL_.jpg",
                "Maja Schöne"
            ),
            containerActors(
                "https://m.media-amazon.com/images/M/MV5BNTE4ZTc3MjUtMTJhMS00OWM1LWIxMmUtYTJlZGU0NGQzYTNlXkEyXkFqcGdeQXVyMjQwMDg0Ng@@._V1_UY44_CR17,0,32,44_AL_.jpg",
                "Stephan Kampwirth"
            )
        )
    )

    private fun containerActors(url: String, text: String) = Container(
        children = listOf(
            imageSmall(url),
            Text(
                text = text,
                textColor = "#0083B3",
                alignment = TextAlignment.LEFT
            )
        )
    ).applyFlex(Flex(flexDirection = FlexDirection.ROW))

    private fun imageSmall(url: String) = Image(
        path = ImagePath.Remote(
            remoteUrl = url,
            placeholder = ImagePath.Local.justMobile("placeholder_small")
        )
    ).applyStyle(
        Style(
            size = Size(
                width = 100.unitReal(),
                height = 80.unitReal(),
                minWidth = 100.unitReal(),
                minHeight = 80.unitReal()
            )
        )
    )
```

### PR DESCRIPTION
**Pull request by jenifersantoszup**
Signed-off-by: jenifer-mathias <jenifer.santos@zup.com.br>

## Description

This PR corrects a behavior of WebView on Android in which it did not set its own size if the user did not enter a size.

## Related Issues

fix #645 

## Tests

I added the following tests:

`webViewClient_should_notify_when_page_stops_loading`

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I signed the [DCO].
- [X] All existing and new tests are passing.
- [X] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [X] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*

[issue database]: https://github.com/ZupIT/beagle/issues
[DCO]: https://developercertificate.org/

### CODE REVIEW

File: android/beagle/src/main/java/br/com/zup/beagle/android/components/WebView.kt [hunk 1]
```diff
@@ -21,11 +21,8 @@ import android.content.Context
 import android.graphics.Bitmap
 import android.net.http.SslError
 import android.view.View
-import android.webkit.SslErrorHandler
-import android.webkit.WebResourceError
-import android.webkit.WebResourceRequest
+import android.webkit.*
```
Comment (botbeaglezup) [inline android/beagle/src/main/java/br/com/zup/beagle/android/components/WebView.kt:24]: <table data-meta="generated_by_android">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/ZupIT/beagle/blob/d3a9732424041843a1336fe582d0978d87f4276a/android/beagle/src/main/java/br/com/zup/beagle/android/components/WebView.kt#L24"></span>android.webkit.* is a wildcard import. Replace it with fully qualified imports.</td>
    </tr>
  </tbody>
</table>

File: android/beagle/src/main/java/br/com/zup/beagle/android/view/YogaLayout.java [hunk 2]
```diff
@@ -200,12 +200,6 @@ public void invalidate(View view) {
         invalidate();
     }
 
-    public void setViewHeight(View view, int height) {
-        if (mYogaNodes.containsKey(view)) {
-            mYogaNodes.get(view).setHeight(height);
-        }
-    }
-
```
Comment (matheusribeirozup) [inline android/beagle/src/main/java/br/com/zup/beagle/android/view/YogaLayout.java:208]: This method has been removed because in BeagleFlexView, YogaLayout's invalidate method is already called by `addOnLayoutChangeListener`, so it has become useless.
