### PR TITLE
fix: iOS binding triggers layout change

### LINKED ISSUE #1011: iOS - SetContext does not change layout
## Description
After a SetContext action fires, the layout is not updated.

## Steps to reproduce
1. Create a Screen with the following content:

- A Container with context
- Text with dynamic size referencing the context in the Container
- a Button with configured SetContext action

2. Fire SetContext

## Expected results
Text should be resized as needed.

## Code example, screenshot, or link to a repository:

```swift
let declarativeScreen = Screen(navigationBar: NavigationBar(title: "Sample", showBackButton: true)) {
    Container(context: Context(id: "context", value: "initial value")) {
        Text("@{context}")
        Button(
            text: "setContext",
            onPress: [
                SetContext(
                    contextId: "context",
                    value: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat"
                )
            ]
        )
    }
}
```

Screenshot:
Captura de Tela 2020-10-07 às 15 51 33

### PR DESCRIPTION
**Pull request by dantes-git**
### Related Issues

Closes #1011 

### Description and Example

As a solution, we need to trigger layout changes whenever the binding value is updated.

### Checklist

Please, check if these important points are met using `[x]`:

- [x] I read the [PR Guide] and followed the process outlined there for submitting this PR.
- [x] I avoided _breaking changes_ by not changing public APIs that people rely on. 
- [x] I am willing to follow-up on review comments in a timely manner.

[PR Guide]: https://github.com/ZupIT/beagle/blob/master/doc/contributing/pull_requests.md

### CODE REVIEW

File: iOS/Sources/Beagle/Sources/Renderer/BeagleScreenViewController.swift [hunk 1]
```diff
@@ -25,14 +25,35 @@ public protocol BeagleControllerProtocol: NSObjectProtocol {
     var screenType: ScreenType { get }
     var screen: Screen? { get }
     
-    func addBinding(_ update: @escaping () -> Void)
+    var bindings: [() -> Void] { get set }
+    func addBinding<T: Decodable>(expression: ContextExpression, in view: UIView, update: @escaping (T?) -> Void)
```
Comment (botbeaglezup) [inline iOS/Sources/Beagle/Sources/Renderer/BeagleScreenViewController.swift:29]: <table data-meta="generated_by_ios">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/ZupIT/beagle/blob/0261cd9fe3f4e14ec5008789346345d66383d47e/iOS/Sources/Beagle/Sources/Renderer/BeagleScreenViewController.swift#L29"></span>Let and var should be separated from other statements by a blank line.<br />
<code>let_var_whitespace</code> <code>BeagleScreenViewController.swift:29</code></td>
    </tr>
  </tbody>
</table>

**Comment by botbeaglezup** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/ZupIT/beagle/blob/0261cd9fe3f4e14ec5008789346345d66383d47e/iOS/Sources/Beagle/Sources/Renderer/BeagleScreenViewController.swift#L74">iOS/Sources/Beagle/Sources/Renderer/BeagleScreenViewController.swift#L74</a> - TODOs should be resolved (This workaround should be remo…).<br />
<code>todo</code> <code>BeagleScreenViewController.swift:74</code></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_ios">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by caioortu — APPROVED** [review]

**Review by lucasaraujo — DISMISSED** [review]

**Review by caioortu — APPROVED** [review]

**Review by lucasaraujo — APPROVED** [review]
