### PR TITLE
fix: Text dark mode behavior

### LINKED ISSUE #766: Text Widget not showing text without expression when in dark mode in BeagleDemo.
## Description
Whenever using the `Text` Widget, either with a declarative or remote(BFF) approach, if the text value used is a simple string like "Text", and not an expression like "@{myContext}", the text if not displayed correctly when using dark mode.

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Set a simple context like `Context(id: "context", value: .string("Text"))`
2. Declare a `Screen` with a `Text("Text")` and a `Text("@{context}")`, for example.
3. See the result using Light mode and Dark mode.

## Expected Results
When changing to dark mode, both `Text`s should be displayed the same way as they are in Light mode. 

## Code example, screenshot, or link to a repository:
```
Screen {
    Container(context: Context(id: "context", value: .string("Text"))) {
        Text("@{context}")
        Text("Text")
    }
}
```

### PR DESCRIPTION
**Pull request by dantes-git**
### Related Issues

Closes #766 

### Checklist

Please, check if these important points are met using `[x]`:

- [x] I read the [PR Guide] and followed the process outlined there for submitting this PR.
- [x] I avoided _breaking changes_ by not changing public APIs that people rely on. 
- [x] I am willing to follow-up on review comments in a timely manner.

[PR Guide]: https://github.com/ZupIT/beagle/blob/master/doc/contributing/pull_requests.md

### CODE REVIEW

**Comment by botbeaglezup** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">The title of PR not follow the rules of: https://www.conventionalcommits.org/en/v1.0.0/</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: iOS/Sources/Beagle/Sources/Components/Text+Renderable/Text+Renderable.swift [hunk 1]
```diff
@@ -31,16 +31,16 @@ extension Text: Widget {
         textView.font = .systemFont(ofSize: 16)
         textView.backgroundColor = .clear
```
Comment (theffc) [inline iOS/Sources/Beagle/Sources/Components/Text+Renderable/Text+Renderable.swift:33]:
```suggestion
        // the order of `observe` here is important (`textColor`should be set before `text`) to avoid a weird UIKit behavior when setting `textColor` to nil (issue: #766)
```
