### PR TITLE
fix: parse color when is RGB size

### LINKED ISSUE #1031: Beagle cannot parse colors in RGB format in APIs 29 and bellow
## Description
When building a component with the `backgroundColor` property assigned to any color in the RGB format, Beagle cannot parse it running in APIs 29 and bellow.

## Steps To Reproduce
1. Use a device with API 29 or bellow.
1. Create a component with style, for example Text with any text;
2. Assign the color #CCC to your backgroundColor;
3. It won't be able to parse

## Expected Results
Beagle is expected to be able to parse colors in RGB, RRGGBB and RRGGBBAA format.

## Code example, screenshot, or link to a repository:
Captura de Tela 2020-10-14 às 00 28 19

### PR DESCRIPTION
**Pull request by matheusribeirozup**
Signed-off-by: Matheus Ribeiro <matheus.ribeiro@zup.com.br>

### Related Issues

Closes #1031 

### Description and Example

This PR fixes the error when colors in the RGB format were not parsed in the Beagle in APIs 29 and bellow.

### Checklist

Please, check if these important points are met using `[x]`:

- [x] I read the [PR Guide] and followed the process outlined there for submitting this PR.
- [x] I avoided _breaking changes_ by not changing public APIs that people rely on. 
- [x] I am willing to follow-up on review comments in a timely manner.

[PR Guide]: https://github.com/ZupIT/beagle/blob/master/doc/contributing/pull_requests.md

### CODE REVIEW

File: android/beagle/src/test/java/br/com/zup/beagle/android/utils/ColorUtilsTest.kt [hunk 1]
```diff
@@ -47,21 +53,19 @@ class ColorUtilsTest {
...
 
         // Then
-        assertEquals("#11BB33",colorSlot.captured)
-
+        assertEquals("#11BB33", colorSlot.captured)
     }
 
     @Test
-    fun hexColor_should_return_AA55CC_when_A5C_is_given() {
+    fun hexColor_should_return_22FF33_when_2F3_is_given() {
```
Comment (viniciusguardieirozup) [inline android/beagle/src/test/java/br/com/zup/beagle/android/utils/ColorUtilsTest.kt:60]: Change to `GIVEN 2F3 WHEN hexCollor is called SHOULD return 22FF33`

**Review by viniciusguardieirozup — CHANGES_REQUESTED** [review]

**Review by uziasferreirazup — APPROVED** [review]

**Review by viniciusguardieirozup — APPROVED** [review]
