### PR TITLE
fix: resize view when inside the scroll layout

### LINKED ISSUE #929: ScrollView does not resize scroll size when child grows
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
The ScrollView component does not resize the scroll size when a child receives context updated to a larger value that increases the size component

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. follow the json return link: https://run.mocky.io/v3/4a98fea2-c03c-4f6d-99af-5d68e17fa2ac
2. run on android platform

## Expected Results
The ScrollView component resizes the scroll size when a child increases in size.

## Code example, screenshot, or link to a repository:
Please provide a link to a repository on GitHub, or provide a minimal code example that reproduces the problem.
You may provide a screenshot of the application if you think it is relevant to your bug report.
Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

### PR DESCRIPTION
**Pull request by uziasferreirazup**
### Related Issues

Closes #929 

### Description and Example

When putting some views inside the scroll view with some layout height change the view not recalculate, create the strategy to inside the scroll view always layout change put the height to auto and dirty all the views.

### Checklist

Please, check if these important points are met using `[x]`:

- [X] I read the [PR Guide] and followed the process outlined there for submitting this PR.
- [X] I avoided _breaking changes_ by not changing public APIs that people rely on. 
- [X] I am willing to follow-up on review comments in a timely manner.

[PR Guide]: https://github.com/ZupIT/beagle/blob/master/doc/contributing/pull_requests.md

### CODE REVIEW

File: android/beagle/src/main/java/br/com/zup/beagle/android/view/custom/BeagleFlexView.kt [hunk 1]
```diff
@@ -47,18 +47,23 @@ internal open class BeagleFlexView(
     var listenerOnViewDetachedFromWindow: (() -> Unit)? = null
 
     fun addView(child: View, style: Style) {
+
         super.addView(child, flexMapper.makeYogaNode(style))
     }
 
-    fun addServerDrivenComponent(serverDrivenComponent: ServerDrivenComponent) {
+    fun addServerDrivenComponent(serverDrivenComponent: ServerDrivenComponent, addLayoutChangeListener: Boolean = true) {
```
Comment (botbeaglezup) [inline android/beagle/src/main/java/br/com/zup/beagle/android/view/custom/BeagleFlexView.kt:54]: <table data-meta="generated_by_android">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/ZupIT/beagle/blob/fe6113072836c57048909ce479827f19d65720e9/android/beagle/src/main/java/br/com/zup/beagle/android/view/custom/BeagleFlexView.kt#L54"></span>Line detected that is longer than the defined maximum line length in the code style.</td>
    </tr>
  </tbody>
</table>

**Comment by botbeaglezup** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Tests have failed, see below for more information.</td>
    </tr>
  </tbody>
</table>

### Tests: 

Name | Classname | Time|
--- | --- | ---|
when_scrollDirection_HORIZONTAL_and_scrollBarEnabled_false_build_should_create_a_scrollView | br.com.zup.beagle.android.components.layout.ScrollViewTest | 0.665|


<p align="right" data-meta="generated_by_android">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by gabrielleonardozup — APPROVED** [review]

**Review by viniciusguardieirozup — APPROVED** [review]

**Review by luisoliveirazup — APPROVED** [review]

**Review by gabrielleonardozup — APPROVED** [review]
