### PR TITLE
fix: fragment transition toolbar glitch

### LINKED ISSUE #839: [Android] Screen transition is presenting some glitches
## Description
We're doing some navigation through our app and we've noticed that some glitches were presented.

## Steps To Reproduce

1. Open sobre server driven screen
2. Click on some button that will start another server-driven screen

## Expected Results
Some soft transitions should be presented.

## Code example, screenshot, or link to a repository:
We got this error
```
E/FragmentManager: No field with the name mListener is found in Animation class
    java.lang.NoSuchFieldException: No field mListener in class Landroid/view/animation/Animation; (declaration of 'android.view.animation.Animation' appears in /system/framework/framework.jar!classes3.dex)
        at java.lang.Class.getDeclaredField(Native Method)
        at android.support.v4.app.FragmentManagerImpl.getAnimationListener(FragmentManager.java:1301)
        at android.support.v4.app.FragmentManagerImpl.animateRemoveFragment(FragmentManager.java:1638)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1548)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
        at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:733)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

```

### PR DESCRIPTION
**Pull request by gabrielleonardozup**
### Related Issues

Closes #839 
### Description and Example
Create a interface to communicate between BeagleFragment and BeagleActivity to send event when fragment is created, this way we can resend this event in BeagleActivity through onServerDrivenContainerStateChanged callback and avoid user to animate toolbar in wrong states.

### Checklist

Please, check if these important points are met using `[x]`:

- [x] I read the [PR Guide] and followed the process outlined there for submitting this PR.
- [x] I avoided _breaking changes_ by not changing public APIs that people rely on. 
- [x] I am willing to follow-up on review comments in a timely manner.

[PR Guide]: https://github.com/ZupIT/beagle/blob/master/doc/contributing/pull_requests.md

### CODE REVIEW

**Comment by botbeaglezup** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">The title of PR not follow the rules of: https://www.conventionalcommits.org/en/v1.0.0/</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by uziasferreirazup — APPROVED** [review]

File: android/beagle/src/main/java/br/com/zup/beagle/android/view/BeagleFragment.kt [hunk 1]
```diff
@@ -53,6 +56,21 @@ internal class BeagleFragment : Fragment() {
         private const val JSON_SCREEN_KEY = "JSON_SCREEN_KEY"
     }
 
+    override fun onAttach(context: Context) {
+        super.onAttach(context)
+        if (context is OnFragmentCallback) {
+            mListener = context
+        } else {
+            throw ClassCastException(context.toString()
+                .toString() + " must implement OnFragmentCallback")
```
Comment (diogooliveira-zup) [inline android/beagle/src/main/java/br/com/zup/beagle/android/view/BeagleFragment.kt:65]: Hi! It`s seems like a second uncessary conversion .toString()

```suggestion
            throw ClassCastException(context.toString() +" must implement OnFragmentCallback")
```

**Review by diogooliveira-zup — CHANGES_REQUESTED** [review]

File: android/beagle/src/main/java/br/com/zup/beagle/android/view/BeagleFragment.kt (hunk 1 above)
Comment (uziasferreirazup) [inline android/beagle/src/main/java/br/com/zup/beagle/android/view/BeagleFragment.kt:65]:
```suggestion
            throw ClassCastException("${context.toString()} must implement OnFragmentCallback")
```

**Review by uziasferreirazup — APPROVED** [review]

**Review by uziasferreirazup — APPROVED** [review]

**Review by viniciusguardieirozup — APPROVED** [review]
