### PR TITLE
fix: PageView component size

### LINKED ISSUE #1522: bug: PagevView tests fail because some elements are not showing on iOS
[PageView tests](https://github.com/ZupIT/beagle/blob/master/tests/appium/project/src/test/resources/features/PageView.feature) are failing on iOS because some elements are not showing on the screen generated by the following JSON (generated by [this code](https://github.com/ZupIT/beagle/blob/master/backend/automated-tests/src/main/kotlin/br/com/zup/beagle/automatedtests/builders/PageViewScreenBuilder.kt)):

```json
{
  "_beagleComponent_" : "beagle:screenComponent",
  "child" : {
    "_beagleComponent_" : "beagle:container",
    "children" : [ {
      "_beagleComponent_" : "beagle:text",
      "text" : "Beagle PageView",
      "style" : {
        "cornerRadius" : { },
        "size" : { },
        "padding" : {
          "bottom" : {
            "value" : 10.0,
            "type" : "REAL"
          }
        },
        "flex" : { }
      }
    }, {
      "_beagleComponent_" : "beagle:text",
      "text" : "Context@{context}"
    }, {
      "_beagleComponent_" : "beagle:button",
      "text" : "Click to go to page three",
      "onPress" : [ {
        "_beagleAction_" : "beagle:setContext",
        "contextId" : "context",
        "value" : 2
      } ]
    }, {
      "_beagleComponent_" : "beagle:pageView",
      "children" : [ {
        "_beagleComponent_" : "beagle:container",
        "children" : [ {
          "_beagleComponent_" : "beagle:text",
          "text" : "Page 1",
          "alignment" : "CENTER"
        }, {
          "_beagleComponent_" : "beagle:text",
          "text" : "@{contextValue}",
          "alignment" : "CENTER"
        } ]
      }, {
        "_beagleComponent_" : "beagle:text",
        "text" : "Page 2",
        "alignment" : "CENTER"
      }, {
        "_beagleComponent_" : "beagle:text",
        "text" : "Page 3",
        "alignment" : "CENTER"
      } ],
      "context" : {
        "id" : "contextValue",
        "value" : "pageViewContext"
      },
      "onPageChange" : [ {
        "_beagleAction_" : "beagle:setContext",
        "contextId" : "context",
        "value" : "@{onPageChange}"
      } ],
      "currentPage" : "@{context}"
    }, {
      "_beagleComponent_" : "beagle:pageIndicator",
      "selectedColor" : "#000000",
      "unselectedColor" : "#888888",
      "numberOfPages" : 3,
      "currentPage" : "@{context}"
    } ],
    "context" : {
      "id" : "context",
      "value" : 0
    },
    "style" : {
      "cornerRadius" : { },
      "size" : {
        "width" : {
          "value" : 100.0,
          "type" : "PERCENT"
        }
      },
      "flex" : { }
    }
  }
}
```

image

### PR DESCRIPTION
**Pull request by lucasaraujo**
### Related Issues
Fix #1522

### Description and Example
[iOS] Make PageView use all available space like Android does.

### Checklist

- [x] I read the [PR Guide] and followed the process outlined there for submitting this PR.
- [x] I avoided _breaking changes_ by not changing public APIs that people rely on. 
- [x] I am willing to follow-up on review comments in a timely manner.
- [x] No documentation changes required.

[PR Guide]: https://github.com/ZupIT/beagle/blob/master/doc/contributing/pull_requests.md

### CODE REVIEW

File: iOS/Sources/Beagle/BeagleTests/Components/ServerDrivenComponent/PageView/PageViewTests.swift [hunk 1]
```diff
@@ -124,7 +124,8 @@ class PageViewTests: XCTestCase {
         
         let pageView = PageView(children: [ComponentDummy()], pageIndicator: nil)
         let view = pageView.toView(renderer: controller.renderer)
-        let page = (view as? PageViewUIComponent)?.pageViewController.viewControllers?.first
+        let componentView = view.subviews.compactMap({ $0 as? PageViewUIComponent }).first
```
Comment (botbeaglezup) [inline iOS/Sources/Beagle/BeagleTests/Components/ServerDrivenComponent/PageView/PageViewTests.swift:127]: <table data-meta="generated_by_ios">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/ZupIT/beagle/blob/874c74ea99476dd1ce7e9c265a6c8ef68eeac157/iOS/Sources/Beagle/BeagleTests/Components/ServerDrivenComponent/PageView/PageViewTests.swift#L127"></span>Trailing closure syntax should be used whenever possible.<br />
<code>trailing_closure</code> <code>PageViewTests.swift:127</code></td>
    </tr>
  </tbody>
</table>

**Review by dantes-git — APPROVED** [review]

**Review by igorgiumellizup — APPROVED** [review]
