### PR TITLE
fix: context in PageView and LazyComponent

### LINKED ISSUE #570: Child controller can not resolve parent context
## Description
When a child controller is created (e.g. PageView pages), it can't use any parent context.

## Steps To Reproduce
1. Create a `PageView` and define its `context`
2. Use the context inside some page

## Expected Results
The page should be able to use PageView context.

## Code example, screenshot, or link to a repository:
```json
{
  "_beagleComponent_": "beagle:pageView",
  "context": {
    "id": "pageview",
    "value": {
      "str": "I'm pageview.str"
    }
  },
  "children": [
    {
      "_beagleComponent_": "beagle:text",
      "text": "=> @{pageview.str}",
      "style": {
        "backgroundColor": "#cccccc"
      }
    }
  ]
}
```
result:

expected:

### LINKED ISSUE #603: Lazy loaded content with context not working
## Description
When the loaded content of a `LazyComponent` has expressions, the expressions won't be evaluated.

## Steps To Reproduce
1. Create a `Container` with `context`.
2. Add a `LazyComponent` as a child, it will return a component using the container context.

## Expected Results
The lazy loaded content should use the container context.

### PR DESCRIPTION
**Pull request by lucasaraujo**
## Description
This PR fix the context in the components PageView and LazyComponent.
In the PageView expression binding were failing because it triggers before the view hierarchy is completed.
In the LazyComponent when the loaded content has expression the binding configuration was missing.

To solve the problems the pending bindings are configured  every time the beagle style/flex triggers.

## Related Issues
Fix #570 
Fix #603 

## Tests

I added the following tests:

PageView test with context
LazyComponent test updated to use context

## Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [DCO].
- [x] All existing and new tests are passing.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.

[issue database]: https://github.com/ZupIT/beagle/issues
[DCO]: https://developercertificate.org/

### CODE REVIEW

**Comment by botbeaglezup** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Big PR</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: iOS/Sources/Beagle/Sources/Components/Lazy+Renderable/Tests/LazyComponentTests.swift [hunk 1]
```diff
@@ -98,6 +104,10 @@ final class LazyComponentTests: XCTestCase {
         }
         XCTAssertEqual(view, initialView)
     }
+    
+    func test_lazyLoadContentWithExpression() {
+        
+    }
```
Comment (gabcoelho) [inline iOS/Sources/Beagle/Sources/Components/Lazy+Renderable/Tests/LazyComponentTests.swift:110]: You left an empty test here
