### PR TITLE
fix: Global context does not clear cache

### LINKED ISSUE #738: Global context with cache problem when the global context value is changed on the screen
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
global context in value passed an object and changing the value of the global context to a new object it cannot update the new value due to the cache

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Follow the link for the use case: https://run.mocky.io/v3/3768663c-582e-4ed1-a237-f1cf62404d6e
2. Follow the example of the gif below, on the second screen when clicking the button the value navigationBar should update to Beagle navigationBar
error_context_global

## Expected Results
global context in value passed an object and changing the global context value to a new object it is able to update the new value.

## Code example, screenshot, or link to a repository:
Use case spoken in the text above

### PR DESCRIPTION
**Pull request by luisoliveirazup**
## Description
After retrieves the value from the global context and updating the value on the same screen, you cannot update the value.

## Related Issues
closes #738 

## Tests

I added the following tests:
the ContextDataManagerTest class was modified to validate that the cache is being cleared when the global context has an update

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [DCO].
- [x] All existing and new tests are passing.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*

[issue database]: https://github.com/ZupIT/beagle/issues
[DCO]: https://developercertificate.org/

### CODE REVIEW

File: android/beagle/src/test/java/br/com/zup/beagle/android/context/ContextDataManagerTest.kt [hunk 1]
```diff
@@ -366,4 +363,31 @@ class ContextDataManagerTest : BaseTest() {
...
+        every { GlobalContext.observeGlobalContextChange(capture(globalContextObserver)) } just Runs
+
+        // When
+        val contextDataManager = spyk<ContextDataManager>(recordPrivateCalls = true)
+        val contexts = contextDataManager.getPrivateField<MutableMap<Int, ContextBinding>>("contexts")
+        contextDataManager.setPrivateField("globalContext", globalContextMock)
+        globalContextObserver.captured.invoke(contextData)
+
+        // Then
+        verify{
```
Comment (matheusribeirozup) [inline android/beagle/src/test/java/br/com/zup/beagle/android/context/ContextDataManagerTest.kt:386]: What do you think of using `verifyOrder`? Because in your method the order in which you invoke the methods makes a difference, consequently this should be something to be tested.
```suggestion
        verifyOrder{
```

File: android/beagle/src/test/java/br/com/zup/beagle/android/context/ContextDataManagerTest.kt [hunk 2]
```diff
@@ -27,12 +27,9 @@ import br.com.zup.beagle.android.testutil.getPrivateField
...
 import br.com.zup.beagle.android.utils.setContextBinding
-import io.mockk.Runs
-import io.mockk.every
-import io.mockk.just
-import io.mockk.mockk
-import io.mockk.mockkObject
-import io.mockk.verify
+import androidx.collection.LruCache
+import br.com.zup.beagle.android.testutil.setPrivateField
+import io.mockk.*
```
Comment (carlossteinzup) [inline android/beagle/src/test/java/br/com/zup/beagle/android/context/ContextDataManagerTest.kt:32]: Remove wildcard

File: android/beagle/src/test/java/br/com/zup/beagle/android/context/ContextDataManagerTest.kt (hunk 1 above)
Comment (luisoliveirazup) [reply android/beagle/src/test/java/br/com/zup/beagle/android/context/ContextDataManagerTest.kt]: change done!

File: android/beagle/src/test/java/br/com/zup/beagle/android/context/ContextDataManagerTest.kt (hunk 2 above)
Comment (luisoliveirazup) [reply android/beagle/src/test/java/br/com/zup/beagle/android/context/ContextDataManagerTest.kt]: change done!
