### PR TITLE
fix: adjust appearance of button when there's no style

### LINKED ISSUE #1338: Button on Beagle Android is not like the Native Android
## Use case

The default Button component on Beagle Android is a lot different than the Native Android Button, here are the diferences:
* The Beagle Button looks like a TextView when implemented. 
* The text label on button is not set to all caps.
* The background color on button is not showing any default color.

### Button Android Beagle
buttonAndroid

### Button Android Native
buttonAndroidNative

## Proposal

* The proposal here is that this difference be analyzed so that we can define a priority to solve it

### PR DESCRIPTION
**Pull request by uziasferreirazup**
### Related Issues

Closes #1338

### Description and Example

when the button didn’t have bff style, it was different from the standard

### Checklist

Please, check if these important points are met using `[x]`:

- [X] I read the [PR Guide] and followed the process outlined there for submitting this PR.
- [X] I avoided _breaking changes_ by not changing public APIs that people rely on. 
- [X] I am willing to follow-up on review comments in a timely manner.

[PR Guide]: https://github.com/ZupIT/beagle/blob/master/doc/contributing/pull_requests.md

### CODE REVIEW

File: android/beagle/src/main/java/br/com/zup/beagle/android/components/Button.kt [hunk 1]
```diff
@@ -78,7 +78,10 @@ data class Button(
             preFetchHelper.handlePreFetch(rootView, it)
         }
 
-        val button = viewFactory.makeButton(rootView.getContext(), styleManager.getButtonStyle(styleId))
+        val style = styleManager.getButtonStyle(styleId)
+
+        val button = if (style == 0) viewFactory.makeButton(rootView.getContext())
+        else viewFactory.makeButton(rootView.getContext(), style)
```
Comment (matheusribeirozup) [inline android/beagle/src/main/java/br/com/zup/beagle/android/components/Button.kt:84]: What do you think about putting `0` in a constant property to make maintenance more intuitive? For example `NO_STYLE`.
```suggestion
        val button = if (style == NO_STYLE) {
            viewFactory.makeButton(rootView.getContext())
        } else {
            viewFactory.makeButton(rootView.getContext(), style)
        }
```
Personally, I think that adding `{}` to the if else and replacing `0` with a constant has little relevance, feel free to decide.

**Review by matheusribeirozup — APPROVED** [review]

**Review by carlossteinzup — APPROVED** [review]
