### PR TITLE
fix: iOS - TextInput enabled custom style config

### LINKED ISSUE #1439: iOS - TextInput enabled custom style
## Description
We should be able to customize `TextInput` to _isEnabled_ (true / false). Currently, it is only possible to configure the initial state of the textinput, future changes do not trigger a layout update.

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Create and register a custom style for TextInput 
2. Create a `TextInput` with this style and a expression for _enabled_ property
3. Change the context containing the _enabled_ value

## Expected Results
The `TextInput` should update your layout properly.

## Code example, screenshot, or link to a repository:
```swift
func customStyle() -> (UITextField?) -> Void {
    return {
        $0?.textColor = ($0?.isEnabled ?? false) ? .blue : .red
    }
}
let theme = AppTheme(styles: ["custom": customStyle])
let dependencies = BeagleDependencies()
dependencies.theme = theme
Beagle.dependencies = dependencies

...

Container(context: Context(id: "enabled", value: true)) {
    TextInput(enabled: "@{enabled}", styleId: "custom")
    Button(text: "update", onPress: [
        SetContext(contextId: "enabled", value: "@{not(enabled)}")
    ])
}
```

### PR DESCRIPTION
**Pull request by dantes-git**
### Related Issues

fixes #1439 

### Description and Example

- Defines a default appearance for `TextInput` enabled (true/false)
- Apply the configured style whenever the enabled bind changes (#1439)

### Checklist

Please, check if these important points are met using `[x]`:

- [x] I read the [PR Guide] and followed the process outlined there for submitting this PR.
- [x] I avoided _breaking changes_ by not changing public APIs that people rely on. 
- [x] I am willing to follow-up on review comments in a timely manner.

[PR Guide]: https://github.com/ZupIT/beagle/blob/master/doc/contributing/pull_requests.md

### CODE REVIEW

File: iOS/Sources/Beagle/Sources/Components/Widget/TextInput/Tests/TextInputTests.swift [hunk 1]
```diff
@@ -112,6 +112,49 @@ class TextInputTests: XCTestCase {
...
+            enabled: "@{textinput.enabled}",
+            styleId: "customStyle",
+            widgetProperties: WidgetProperties(style: .init(size: Size().width(100).height(50)))
+        )
+        
+        func customStyle() -> (UITextField?) -> Void {
+            return {
+                $0?.textColor = ($0?.isEnabled ?? false) ? .blue : .red
+            }
+        }
```
Comment (gabcoelho) [inline iOS/Sources/Beagle/Sources/Components/Widget/TextInput/Tests/TextInputTests.swift:146]: i think it would be nice to have this example somewhere in BeagleDemo as well, but I'll approve it anyways 😁

**Review by gabcoelho — APPROVED** [review]

**Review by lucasaraujo — APPROVED** [review]

File: iOS/Sources/Beagle/Sources/Components/Widget/TextInput/Tests/TextInputTests.swift (hunk 1 above)
Comment (dantes-git) [reply iOS/Sources/Beagle/Sources/Components/Widget/TextInput/Tests/TextInputTests.swift:146]: We currently do not have a section with `TextInput` samples, the right thing to do is to add all examples involving textinput in Demo and update in the doc. We can see this in a future pr.
