### PR TITLE
fix: flutter: tabbar and image

### LINKED ISSUE #1660: [Flutter] No error logging when component fails to render
For some reason, when the component builder fails to build the component, nothing happens, no error is logged. The screen gets stuck on "Loading..."  and there's no clue of what happened.

We should get Flutter to log something, is this error being silently catch?

Example: if I try to create a component and pass the wrong types to the parameters, there should be a cast exception, but nothing happens.

### PR DESCRIPTION
**Pull request by Tiagoperes**
### Related Issues

#1643 
closes #1660 

### Description and Example

- The contract states that `onTabChange` receives a single `Int` as parameter. The component was passing an object with the property `value: Int`. It has been fixed.
- There were many problems related to the absence of verifications for nulls. They have all been fixed (I hope).
- Renamed `TabBar.TabBarItem.path` to `TabBar.TabBarItem.icon` so it's the same as the component's description in the documentation.
- Replaced the logic  to build an Icon inside the TabBar by the BeagleImage component, which already contains this logic.
- Fixed the icon size in the TabBar to 32px height.
- Added `style` to the component BeagleImage so the image size can be parametrized. Currently, only `UnitType.REAL` is supported.
- The default `mode` for the BeagleImage was `CENTER`. For all other platforms, the default is `FIT_CENTER`, so I changed it. There is a problem regarding the mode `FIT_CENTER`, I created [an issue for this](https://github.com/ZupIT/beagle/issues/1665).
- Added error log to the BeagleImage component when the `mobileId` is not found.
- Fixed #1660: now, when an error happens inside the function to build a component, it gets logged. Instead of doing nothing, it returns an UndefinedComponent.
- The tests have been updated to reflect these changes.

### Checklist

Please, check if these important points are met using `[x]`:

- [x] I read the [PR Guide] and followed the process outlined there for submitting this PR.
- [ ] I avoided _breaking changes_ by not changing public APIs that people rely on. 
- [x] I am willing to follow-up on review comments in a timely manner.
- [ ] I have made the documentation changes or I created an issue explaining how to document this change on [Docs issues](https://github.com/ZupIT/beagle-docs/issues). Please link the issue here:

[PR Guide]: https://github.com/ZupIT/beagle/blob/master/doc/contributing/pull_requests.md

### CODE REVIEW

**Comment by botbeaglezup** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/ZupIT/beagle/blob/6c8660c60996999cfcc3d30b83be9a6c1c265923/beagle_components/lib/beagle_tab_bar.dart#L53">beagle_components/lib/beagle_tab_bar.dart#L53</a> - The value of the field '_logger' isn't used</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_flutter">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by uziasferreirazup — DISMISSED** [review]

File: flutter/beagle_components/lib/beagle_tab_bar.dart [hunk 1]
```diff
@@ -82,20 +90,18 @@ class _BeagleTabBarState extends State<BeagleTabBar>
...
 
   List<BottomNavigationBarItem> buildCupertinoTabs() {
     return widget.items.map((tabBarItem) {
       return BottomNavigationBarItem(
-        label: tabBarItem.title,
-        icon: _getImageFromAsset(
-          tabBarItem.path.mobileId,
-        ),
+        label: tabBarItem.title ?? '',
+        icon: tabBarItem.icon == null
```
Comment (matheusribeirozup) [inline flutter/beagle_components/lib/beagle_tab_bar.dart:102]: The `icon` attribute from `BottomNavigationBarItem` is required, it can't be null.

**Review by matheusribeirozup — CHANGES_REQUESTED** [review]

File: flutter/beagle_components/lib/beagle_tab_bar.dart (hunk 1 above)
Comment (Tiagoperes) [reply flutter/beagle_components/lib/beagle_tab_bar.dart:102]: Fixed!

**Review by matheusribeirozup — APPROVED** [review]

**Review by uziasferreirazup — APPROVED** [review]
