### PR TITLE
fix: adjust the type declaration method of the textInput component

### LINKED ISSUE #1123: bug: the type email and type text attribute of the textInput component does not work correctly
## Description
When passing the type EMAIL or TEXT attribute of the textInput component via bind, the text typed is duplicated on devices with API prior to 30.

## Steps To Reproduce
1. Create a native screen or BFF with the textInput component and with the attribute of type EMAIL or TEXT passed via context.

## Expected Results
When entering a value via physical keyboard, the text will be duplicated.

## Code example, screenshot, or link to a repository:
Captura de tela de 2020-11-09 11-56-54

textinput

### PR DESCRIPTION
**Pull request by jenifersantoszup**
### Related Issues
Closes #1123  

### Description and Example
The method responsible for declaring the types of the textInput component has been changed to suit the scenario of its use via context.

### Checklist

Please, check if these important points are met using `[x]`:

- [x] I read the [PR Guide] and followed the process outlined there for submitting this PR.
- [x] I avoided _breaking changes_ by not changing public APIs that people rely on. 
- [x] I am willing to follow-up on review comments in a timely manner.

[PR Guide]: https://github.com/ZupIT/beagle/blob/master/doc/contributing/pull_requests.md

### CODE REVIEW

File: android/beagle/src/test/java/br/com/zup/beagle/android/components/TextInputTest.kt [hunk 1]
```diff
@@ -107,32 +106,73 @@ class TextInputTest : BaseComponentTest() {
...
+
+        // When
+        val textInput = callTextInput(type)
+        textInput.buildView(rootView)
+
+        // Then
+        verify(exactly = 1) { editText.setRawInputType(InputType.TYPE_CLASS_TEXT or InputType.TYPE_TEXT_FLAG_CAP_SENTENCES) }
+    }
+
+}
```
Comment (uziasferreirazup) [inline android/beagle/src/test/java/br/com/zup/beagle/android/components/TextInputTest.kt:178]: What do you think to follow the new pattern to write new tests? 
https://github.com/ZupIT/beagle/wiki/Android-Tests-Style-Guide

**Review by danilorochazup — APPROVED** [review]

**Review by uziasferreirazup — APPROVED** [review]
