### PR TITLE
fix: add focus in component text input

### LINKED ISSUE #936: TextInput not clickable
## Description
When clicking in component `TextInput` the keyboard not showing

## Steps To Reproduce
Clone the internal project and declare the component  `TextInput`

## Expected Results
The user can put the text in the component

## Code example, screenshot, or link to a repository:
https://github.com/ZupIT/mfi-app-mobile

### PR DESCRIPTION
**Pull request by uziasferreirazup**
### Related Issues

Closes #936 

### Description and Example

In some applications, the component `TextInput` didn't has focusing, set programmatically the possible to component has a focus

### Checklist

Please, check if these important points are met using `[x]`:

- [X] I read the [PR Guide] and followed the process outlined there for submitting this PR.
- [X] I avoided _breaking changes_ by not changing public APIs that people rely on. 
- [X] I am willing to follow-up on review comments in a timely manner.

[PR Guide]: https://github.com/ZupIT/beagle/blob/master/doc/contributing/pull_requests.md

### CODE REVIEW

**Review by jefersonlopeszup — DISMISSED** [review]

File: android/beagle/src/main/java/br/com/zup/beagle/android/components/TextInput.kt [hunk 1]
```diff
@@ -93,6 +93,8 @@ data class TextInput(
         styleManagerFactory.getInputTextStyle(styleId)
     ).apply {
         textInputView = this
+        isFocusable = true
```
Comment (tuliopereirazup) [inline android/beagle/src/main/java/br/com/zup/beagle/android/components/TextInput.kt]: What do you think do put a test case for this one?

File: android/beagle/src/main/java/br/com/zup/beagle/android/components/TextInput.kt [hunk 2]
```diff
@@ -93,6 +93,8 @@ data class TextInput(
...
+        isFocusableInTouchMode = true
```
Comment (matheusribeirozup) [inline android/beagle/src/main/java/br/com/zup/beagle/android/components/TextInput.kt:97]: What do you think of adding a unit test to validate that these flags are enabled?

Comment (uziasferreirazup) [reply android/beagle/src/main/java/br/com/zup/beagle/android/components/TextInput.kt]: I just updated the unit tests...

**Review by tuliopereirazup — APPROVED** [review]

**Review by matheusribeirozup — APPROVED** [review]

**Comment by matheusribeirozup** [comment]
This PR is pointing to master

**Review by matheusribeirozup — CHANGES_REQUESTED** [review]
This PR is pointing to master

**Review by matheusribeirozup — APPROVED** [review]
