### PR TITLE
fix: extension function loadView to viewgroups with wrap_content height

### LINKED ISSUE #217: ViewGroup.loadView is not working as expected if height is wrap_content
## Describe the problem
When we use the ViewGroup.loadView and the container height is set to use `wrap_content`, the layout is not calculate correctly and does not update the size.

## Expected behaviuor
After the view is updated, we need to trigger the onLayout and onMeasure again to calculate the ViewGroup size.

### PR DESCRIPTION
**Pull request by matheusribeirozup**
**Description**
When the extension function `loadView` was called from a viewgroup with `wrap_content` height, Beagle did not render the content.

**Issue**
Fix #217 

BREAKING CHANGE: The extension function `setBeagleStateChangedListener` has been incorporated into `loadView`

### CODE REVIEW

File: android/beagle/src/main/java/br/com/zup/beagle/utils/ViewGroupExtensions.kt [hunk 1]
```diff
@@ -21,34 +21,42 @@ import android.view.View
...
 import br.com.zup.beagle.view.ScreenRequest
 import br.com.zup.beagle.view.StateChangedListener
 
 internal var beagleSerializerFactory = BeagleSerializer()
 
-fun ViewGroup.loadView(activity: AppCompatActivity, screenRequest: ScreenRequest) {
-    loadView(this, ActivityRootView(activity), screenRequest)
+fun ViewGroup.loadView(activity: AppCompatActivity,
+                       screenRequest: ScreenRequest,
+                       listener: StateChangedListener? = null
```
Comment (tuliopereirazup) [inline android/beagle/src/main/java/br/com/zup/beagle/utils/ViewGroupExtensions.kt:37]: What do you think to use High-Order function instead a interface?

Comment (matheusribeirozup) [reply android/beagle/src/main/java/br/com/zup/beagle/utils/ViewGroupExtensions.kt:37]: Thanks for the tip! Changes done
