### PR TITLE
fix: textInput onBlur

### LINKED ISSUE #900: [iOS] - TextInput onBlur event does not work
## Description
onBlur event of TextInput its not called when return button its pressed on the keyboard in none of the input types

## Steps To Reproduce

1. Declare a textinput 
2. Input some text on it
3. press return key of the keyboard. 
4. onBlur event will not be called

## Expected Results
Its expected to call the actions passed at the onBlur events when pressed return button. The most common use case its the when we want to dismiss the keyboard by tapping return.

## Source of the problem
The execution of actions its being called at textFieldDidEndEditing but this delegate method its called only when we call `resignFirstReponder()` method in a `UITextField` which its never called during the execution time.

## Possible solution 
Maybe we can call `resignfirstReponder()` at `textFieldShouldReturn()` delegate method.
It would be cool to add a boolean atribute to textinput that tells if it should dismiss the keyboard onBlur, so there is no need to create a custom action to do so

### PR DESCRIPTION
**Pull request by caioortu**
### Related Issues

Closes #900 

### Checklist

Please, check if these important points are met using `[x]`:

- [x] I read the [PR Guide] and followed the process outlined there for submitting this PR.
- [x] I avoided _breaking changes_ by not changing public APIs that people rely on. 
- [x] I am willing to follow-up on review comments in a timely manner.

### CODE REVIEW

**Comment by theffc** [comment]
@yandiaszup do you think this solution would work for you?

**Review by lucasfonsecazup — DISMISSED** [review]

File: iOS/Sources/Beagle/Sources/Components/TextInput+Renderable/TextInput.swift [hunk 1]
```diff
@@ -104,26 +104,30 @@ extension TextInput: ServerDrivenComponent {
...
-            textField.text = updatedText
-            textChanged()
+            
+            textChanged(updatedText)
             
             let value: DynamicObject = .dictionary(["value": .string(updatedText ?? "")])
             controller?.execute(actions: onChange, with: "onChange", and: value, origin: self)
             
-            return false
+            return true
```
Comment (dantes-git) [inline iOS/Sources/Beagle/Sources/Components/TextInput+Renderable/TextInput.swift:123]: Here we cannot return true because if a textinput is using binding, it will be updated twice. Example:

```swift 
TextInput(
    value: "@{context1}",
    onChange: [
        SetContext(
            contextId: "context1",
            value: "@{onChange.value}"
        )
    ]
)
```
We need to creat a test for this.

**Review by dantes-git — CHANGES_REQUESTED** [review]

**Review by dantes-git — APPROVED** [review]

**Review by yandiaszup — APPROVED** [review]
